### ISSUE TITLE
Does this actually works?

### ISSUE THREAD

**Issue by algorni** [Umlatt/vdo.ninja#2]
...basically you didn't start the nginx from the scripts.

...and it can't accept HTTPS request. 

Does this works?!?

**Comment by Umlatt** [comment]
At last test it was working as required.

Please provide some logs/screenshots/information to indicate where you are having an issue.

**Comment by Umlatt** [comment]
Answers to your queries

1. Nginx is auto-started as part of the default Nginx configuration in the Nginx docker image (which is used as the source image upon which the package is deployed).
2. SSL & HTTPS is handled by the addition of certbot, which takes a `valid` DNS name and does a registration on your behalf.

**Comment by Umlatt** [comment]
My apologies. You are quite correct about step 1.
I had overwritten the nginx command on boot.
It does, in fact, start up the first time, however, after reboots it is not started.

This will be addressed in the next revision.

**Comment by Umlatt** [comment]
The latest available build now works as desired. *Please see additional of restart unless stopped in deployment (works around unexpected nginx behaviours)
