### ISSUE TITLE
Updating After vdo.ninja Updates

### ISSUE THREAD

**Issue by ASchneiderBR** [Umlatt/vdo.ninja#3]
First of all, great job on this Docker container! I got it running on the first try on an Alpine LXC container on my Proxmox home server.

I'm wondering what the process is for updating this Docker container after Steve releases an update for the main vdo.ninja project. 

A few specific questions:

- Is there an automated build set up that will rebuild the Docker image when the main repo is updated? Or does it need to be manually updated each time?

- For those who already have the container running, is simply stopping the old container and starting a new one with the latest image enough to update? Or will any additional steps be required?

Overall just interested in what the process looks like for staying up-to-date with the main vdo.ninja releases using this great Docker container. 

Thank you very much.

**Comment by Umlatt** [comment]
Hi. Thanks for the interest.

- For now, I just run a manual build when Steve releases an official stable release on Github (not super efficient, but it seems ok for now).
I have, however, been wanting to deliver an automation pipeline to build & push an edge release type release based on when Steve merges to the master branch but I have been going down a rabbit hole of what is the best way to deliver that across Github projects. Honestly though, I haven't had anyone really ask me for it yet, but would be happy to pick up the thread if there is interest.
- I tried to build the update process a drop-in replacement (however, if Steve is allowing for custom settings saves, I can update the container to persist that data accordingly). Long story short... it should be a simple image pull -> run to update to the latest release.

I am very happy to hear that you're getting some joy from it. 

Have a great day,
regards,
Richard

**Comment by Umlatt** [comment]
Honestly, though, it probably makes more sense for Steve to just absorb this project into the main project, and then using github runners are straight forward.

**Comment by ASchneiderBR** [comment]
Hi Richard,

Thank you so much for the helpful information on updating the container. I really appreciate you taking the time to explain the current process.

I also think your idea of having automated edge builds when changes are merged to the main vdo.ninja repo is a good one. As a user, I would certainly welcome being able to easily spin up containers from the latest code. But no pressure - I'm sure you have lots of great ideas and only so much time!

Thanks again for all your work on this container. Being able to easily run vdo.ninja in Docker on my home server has been really fun. Steve has created an awesome project.

Please keep up the excellent work, and let me know if there is ever anything I can do to help with testing or feedback!

Best regards.

**Comment by ASchneiderBR** [comment]
Hi Richard,

Thank you so much for the helpful information on updating the container. I really appreciate you taking the time to explain the current process.

I also think your idea of having automated edge builds when changes are merged to the main vdo.ninja repo is a good one. As a user, I would certainly welcome being able to easily spin up containers from the latest code. But no pressure - I'm sure you have lots of great ideas and only so much time!

Thanks again for all your work on this container. Being able to easily run vdo.ninja in Docker on my home server has been really fun. Steve has created an awesome project.

Please keep up the excellent work, and let me know if there is ever anything I can do to help with testing or feedback!

Best regards.
